name: CD_workflow
on: 
  push:
    branches:
      - 'cicd/cd'

jobs:
  cd:
    runs-on: windows-latest
    env:
      ssh_key: ${{ secrets.SSH_KEY }}
    steps: 
      - uses: actions/checkout@v4
      - run: ssh -o StrictHostKeyChecking=no bdb2c2023q4_guest_3@brain-client.bigdatateam.org
      - run: echo OK
      - run: python hello.py