name: CD_workflow
on: 
  push:
    branches:
      - 'cicd/cd'

jobs:
  cd:
    runs-on: windows-latest
    steps: 
      - name: Set environment variables
      - env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          SSH_KEY_PATH: ${{ github.workspace }}~/.ssh/id_rsa
      - uses: actions/checkout@v4
      - name: Create SSH key
      - run: mkdir ~/.ssh/
      - run: echo "$SSH_KEY" > ~/.ssh/id_rsa
            echo "SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      # - run: ssh -o StrictHostKeyChecking=no bdb2c2023q4_guest_3@brain-client.bigdatateam.org
      - run: ssh -i $SSH_KEY_PATH bdb2c2023q4_guest_3@brain-client.bigdatateam.org ls
      - run: echo OK
      # - run: python hello.py
